[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PlotlyJS = "f0f68f2c-8dec-58d4-8b6b-1c8b10d9113c"
SimJulia = "428bdadb-6287-5aa5-874b-9969638295fd"

[compat]
Plots = "1.38"
PlotlyJS = "0.18"
julia = "1.6"
