name = "FreightDispatchSimulator"
uuid = "2f3a4b5c-6d7e-8f9a-b0c1-d2e3f4a5b6c7"
version = "0.2.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ResumableFunctions = "c5292f4c-5179-55e1-98c5-05642aab7184"
SimJulia = "428bdadb-6287-5aa5-874b-9969638295fd"

[compat]
PlotlyJS = "0.18.16"
Plots = "1.38"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
